### ISSUE TITLE
Consul issue

### ISSUE THREAD

**Issue by brunowego** [Allenxuxu/microservices#1]
Hi @Allenxuxu, nice to meet you! I'm learning with your code, thanks for share!

Can you help me with the issue below?

```
$ make run                                                                                                                                                   
go build -o ../../build/userAPI main.go
../../build/userAPI  --registry=consul
2019/05/03 21:32:48 error loading source consul: source not found: /micro/config/
make: *** [run] Error 1
```

**Comment by Allenxuxu** [comment]
Hi @Bruno Wego!
microservices/api/user/main.go 
```
token := &token.Token{}
token.InitConfig("127.0.0.1:8500", "micro", "config", "jwt-key", "key")
```
I use consul as a configuration center to dynamically change the private key. So you need run consul, and set KV.
![image](https://user-images.githubusercontent.com/20566897/57171729-bc294500-6e49-11e9-8345-6b6a07c520fd.png)

I will improve the documentation as soon as possible.

**Comment by Allenxuxu** [comment]
> Hi @Allenxuxu, nice to meet you! I'm learning with your code, thanks for share!
> 
> Can you help me with the issue below?
> 
> ```
> $ make run                                                                                                                                                   
> go build -o ../../build/userAPI main.go
> ../../build/userAPI  --registry=consul
> 2019/05/03 21:32:48 error loading source consul: source not found: /micro/config/
> make: *** [run] Error 1
> ```

Hi @Bruno Wego!
microservices/api/user/main.go 
```
token := &token.Token{}
token.InitConfig("127.0.0.1:8500", "micro", "config", "jwt-key", "key")
```
I use consul as a configuration center to dynamically change the private key. So you need run consul, and set KV.
![image](https://user-images.githubusercontent.com/20566897/57171729-bc294500-6e49-11e9-8345-6b6a07c520fd.png)

I will improve the documentation as soon as possible.

**Comment by brunowego** [comment]
Thanks @brunowego 💯
