### ISSUE TITLE
trace的一些问题

### ISSUE THREAD

**Issue by jhzlf** [Allenxuxu/microservices#10]
首先，感谢例子，受益良多。
调用Inject时候，应该使用sp.Tracer().Inject，否则在jaeger中链路无法串起来。

**Comment by Allenxuxu** [comment]
> 首先，感谢例子，受益良多。
> 调用Inject时候，应该使用sp.Tracer().Inject，否则在jaeger中链路无法串起来。

感谢反馈。 能否详细点说明，或者提个 PR 上来。

**Comment by Allenxuxu** [comment]
https://github.com/Allenxuxu/microservices/pull/11

已经合并了，感谢PR
