### ISSUE TITLE
关于micro分布式部署的问题

### ISSUE THREAD

**Issue by kwzcoder** [Allenxuxu/microservices#16]
背景:  想实现在三台服务器主机完成微服务分布式部署 
目标:  其中任意一台服务器宕机不影响整个业务使用
![image](https://user-images.githubusercontent.com/13954932/78114365-bceca180-7433-11ea-8679-2f923558d623.png)

准备工作:  在三台服务器上完成consul 集群部署
![image](https://user-images.githubusercontent.com/13954932/78111746-b1977700-742f-11ea-9a49-8255e46fefb8.png)
现在server1上 , 运行 micro api ,  hello-srv, hello-api 工作正常 , http://192.168.0.1:8080/hello 接口访问成功

然后我尝试在server2 上重复server1操作 ,同样指定 --registry=consul --registry_address=192.168.0.1:8500,
但是发现访问http://192.168.0.1:8080/hello,  server1中    micro api log  会出现: 

2020-04-01 03:44:47.493251 I | hystrix breaker err:  hystrix: timeout
2020-04-01 03:44:47.493531 I | http: proxy error: context canceled
2020-04-01 03:44:47.493547 I | status code 502

而且server2中的也没有接受到请求

所以现在有几个问题想请教一下:
1. 如果想达成任意一台服务器宕机不影响整个业务使用的目的, 我应该怎么部署应用, 是不是应该每一个server 都要部署一个 micro api ,  hello-srv, hello-api ?
2. 在server 1-3 中  registry_address该怎样指定?
3. 部署完成后,   访问接口http://192.168.0.1:8080/hello接口里的ip是 server1 还是 server2 或 server3 ?

**Comment by Allenxuxu** [comment]
>  问http://192.168.0.1:8080/hello 这样本来就访问不到的吧。。先理解 micro 的路由规则

基于 micro 的所有服务都可以冗余部署，只要网络互通，可以每台机器上都部署就可以了。需要主要的 micro api 服务，是一个网关，通过 192.168.0.1:8080，就是指定了访问某一台机器的服务了。一般可以在前面再加负载均衡（软硬件）。

**Comment by kwzcoder** [comment]
感谢回复,   现在知道问题所在了,   我之前没有表述清楚,因为hello-srv, hello-api都是用docker 部署,注册到consul后address是容器的ip ,所以会出现502 ,   在micro 中国站微信群里请教得出解决方案:
   1.  Dockerfile 中指定 "ENTRYPOINT /hello-api --server_address=host2的ip:port"
   2. docker  run  --net=host
