### ISSUE TITLE
userSRV 服务启动报错

### ISSUE THREAD

**Issue by dxianghai** [Allenxuxu/microservices#3]
consul服务器不在本地主机userSRV无法启动一起报错
protoc --proto_path=/Users/allen/dev/go/src:. --micro_out=. --go_out=. proto/user/user.proto
go build -o ../../build/userSRV main.go
../../build/userSRV  --registry=consul --registry_address=192.168.31.30:8500
2019/05/20 15:27:43 error loading source consul: Get http://127.0.0.1:8500/v1/kv/micro/config/?recurse=: dial tcp 127.0.0.1:8500: connect: connection refused
make: *** [run] Error 1

**Comment by Allenxuxu** [comment]
@dxianghai  需要修改一下代码，我在代码中使用了consul 的 KV 来模拟配置中心, 动态更新JWT的私钥

在main函数里， 把 127.0.0.1 改了 就可以了
```
...
	token := &token.Token{}
	token.InitConfig("127.0.0.1:8500", "micro", "config", "jwt-key", "key")
	pb.RegisterUserServiceHandler(service.Server(), handler.New(token))
...
```

**Comment by dxianghai** [comment]
所有的配置都确定改了的,
token := &token.Token{}
	token.InitConfig("192.168.31.3:8500", "micro", "config", "jwt-key", "key")
	pb.RegisterUserServiceHandler(service.Server(), handler.New(token))
只要handler.New(token)就会报这个错误,

**Comment by Allenxuxu** [comment]
本机确定能ping通这个ip吗

**Comment by dxianghai** [comment]
其它几个服务正常的,只有这个userSRV怎么修改注册中心都不行,你可以重现一下,把consul安装在独立的虚拟机中,

**Comment by Allenxuxu** [comment]
好，我明早试一下，这会上床了。 你把你那个服务的 main.go 贴一下

**Comment by dxianghai** [comment]
package main

import (
	"fmt"
	"time"

	"allen/micro/microservices/lib/token"
	"allen/micro/microservices/lib/tracer"
	_ "allen/micro/microservices/srv/user/db"
	"allen/micro/microservices/srv/user/handler"
	pb "allen/micro/microservices/srv/user/proto/user"

	"github.com/micro/go-grpc"
	"github.com/micro/go-log"
	"github.com/micro/go-micro"
	ocplugin "github.com/micro/go-plugins/wrapper/trace/opentracing"
	opentracing "github.com/opentracing/opentracing-go"
)

const name = "go.micro.srv.user"

func main() {
	fmt.Println("Hello world !!")
	
	t, io, err := tracer.NewTracer(name, "192.168.31.3:6831")
	if err != nil {
		log.Fatal(err)
	}
	defer io.Close()
	opentracing.SetGlobalTracer(t)

	service := grpc.NewService(
		micro.Name(name),
		micro.Version("latest"),
		micro.RegisterTTL(time.Second*15),
		micro.RegisterInterval(time.Second*10),
		micro.WrapHandler(ocplugin.NewHandlerWrapper(opentracing.GlobalTracer())),
	)
	service.Init()

	token := &token.Token{}
	token.InitConfig("192.168.31.3:8500", "micro", "config", "jwt-key", "key")
	pb.RegisterUserServiceHandler(service.Server(), handler.New(token))

	if err := service.Run(); err != nil {
		log.Fatal(err)
	}
}
就只改变了注册中心的地址,其它没变 fmt.Println("Hello world !!") 都打印不出来,直接报错(dial tcp 127.0.0.1:8500: connect: connection refused)

**Comment by dxianghai** [comment]
找到问题了,user/db/user.go下的DB初始化init()配置问题导致的,因为默认是从本地consul拉取

**Comment by Allenxuxu** [comment]
这边确认是个问题，我来改下。谢谢指出。

**Comment by dxianghai** [comment]
客气啦,向你学习了
