### ISSUE TITLE
能提供下联系方式一起交流吗

### ISSUE THREAD

**Issue by jinbanglin** [Allenxuxu/microservices#4]
Go micro 微服务实战 QQ群184572648

**Comment by Allenxuxu** [comment]
可以的啊，官方有slack  ，也有个微信群的。  你这个qq群搜不到啊

**Comment by jinbanglin** [comment]
我QQ   570751295  加我我拉你进群嘛

**Comment by jinbanglin** [comment]
![Go micro 微服务实战群聊二维码](https://user-images.githubusercontent.com/38064171/60241561-2dcfbd80-98e6-11e9-8b3c-a50b85a00948.png)

**Comment by Allenxuxu** [comment]
ok， 申请加群了

**Comment by skw0823** [comment]
可以把我拉进微信群吗18520345020
