### ISSUE TITLE
要是能出个细致的教程就好了！

### ISSUE THREAD

**Issue by 9act** [Allenxuxu/microservices#5]

**Comment by Allenxuxu** [comment]
@1458790210 
有相应的博客讲解的，https://note.mogutou.xyz/category/go-micro

**Comment by 9act** [comment]
你好！看了你的博客，有几个问题想请教，按照你的dockfile build后去创建容器，一直停留在preparing状态，拉你的镜像就没问题，请问什么原因呢，另外我用go mod依赖写的micro服务，该如何写dockfile呢？请教！

**Comment by Allenxuxu** [comment]
@1458790210 
问题1:  贴一下你 build 的命令，和出错信息

问题2: go mod 和 写 dockefile 没有关系，go 都是静态编译成二进制的，打到镜像里的只有可执行文件，没有依赖。
