### ISSUE TITLE
关于micro api的一些问题

### ISSUE THREAD

**Issue by yiippee** [Allenxuxu/microservices#9]
感谢你写的go-micro例子，关于micro api想请教一下啊：1，micro api 你把auth trace breaker 等中间件全部让api网关执行，会影响性能么？2，micro api 感觉是所有请求的入口，如果网关后端对应着几十个服务，所有的请求都走网关，会不会成为性能瓶颈啊，对网关可以做负载均衡吗？还有如何防单点故障呢？对于api网关我一直困惑这几点。谢谢。

**Comment by Allenxuxu** [comment]
> 感谢你写的go-micro例子，关于micro api想请教一下啊：1，micro api 你把auth trace breaker 等中间件全部让api网关执行，会影响性能么？2，micro api 感觉是所有请求的入口，如果网关后端对应着几十个服务，所有的请求都走网关，会不会成为性能瓶颈啊，对网关可以做负载均衡吗？还有如何防单点故障呢？对于api网关我一直困惑这几点。谢谢。

网关都是无状态的，可以冗余部署，在api网关前面肯定需要做负载均衡的，可以是 nginx 或者 硬件负载均衡。

**Comment by yiippee** [comment]
是这样的，一般会用nginx对网关负载均衡。再请问一下，一个网关一般来说后端可以带多少个业务服务呢？比如说，假设一个网关可以带10个业务服务，那么如果有30个业务服务，那么就需要3个网关了，这只是我的一种猜想。实际情况下，大概的比例是多少呢？不需要特别的场景，一般的就可以，就平常的比如电商吧，涉及到读写DB等。因为没有实际的使用经验，所以不是体会很深。谢谢。

**Comment by Allenxuxu** [comment]
> 是这样的，一般会用nginx对网关负载均衡。再请问一下，一个网关一般来说后端可以带多少个业务服务呢？比如说，假设一个网关可以带10个业务服务，那么如果有30个业务服务，那么就需要3个网关了，这只是我的一种猜想。实际情况下，大概的比例是多少呢？不需要特别的场景，一般的就可以，就平常的比如电商吧，涉及到读写DB等。因为没有实际的使用经验，所以不是体会很深。谢谢。

我也没有多少经验啊，哈哈。
这种情况，一般和请求量和速率有关，会根据压力测试来定吧。
